"""
Minimal main.py for ai_send_text_assistant_message
Auto-generated by Firebase Functions Build Tool
"""

# Import the function from its original location
from api.http.text_assistant.send_text_assistant_message import ai_send_text_assistant_message
# Expose only this function for Firebase deployment
__all__ = ["ai_send_text_assistant_message"]
